server:
  port: 9090
spring:
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  application:
    name: carhaul-auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/carhaul
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs



jwt:
  auth:
    converter:
      resource-id: authentication
      principal-attribute: preferred_username



